---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/demo/model/a1_ign/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/a1_ign/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/a1_ign/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/forces/FL_contact_force"
  gz_topic_name: "/world/demo/model/a1_ign/link/FL_calf/sensor/contact_sensor_FL/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS  
- ros_topic_name: "/forces/FR_contact_force"
  gz_topic_name: "/world/demo/model/a1_ign/link/FR_calf/sensor/contact_sensor_FR/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS  
- ros_topic_name: "/forces/RL_contact_force"
  gz_topic_name: "/world/demo/model/a1_ign/link/RL_calf/sensor/contact_sensor_RL/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS  
- ros_topic_name: "/forces/RR_contact_force"
  gz_topic_name: "/world/demo/model/a1_ign/link/RR_calf/sensor/contact_sensor_RR/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS  
- ros_topic_name: "/FL_hip_cmd"
  gz_topic_name: "/model/a1_ign/joint/FL_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/FL_thigh_cmd"
  gz_topic_name: "/model/a1_ign/joint/FL_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/FL_calf_cmd"
  gz_topic_name: "/model/a1_ign/joint/FL_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/FR_hip_cmd"
  gz_topic_name: "/model/a1_ign/joint/FR_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/FR_thigh_cmd"
  gz_topic_name: "/model/a1_ign/joint/FR_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/FR_calf_cmd"
  gz_topic_name: "/model/a1_ign/joint/FR_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/RL_hip_cmd"
  gz_topic_name: "/model/a1_ign/joint/RL_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/RL_thigh_cmd"
  gz_topic_name: "/model/a1_ign/joint/RL_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/RL_calf_cmd"
  gz_topic_name: "/model/a1_ign/joint/RL_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/RR_hip_cmd"
  gz_topic_name: "/model/a1_ign/joint/RR_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/RR_thigh_cmd"
  gz_topic_name: "/model/a1_ign/joint/RR_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/RR_calf_cmd"
  gz_topic_name: "/model/a1_ign/joint/RR_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- gz_topic_name: /model/a1_ign/odometry
  ros_topic_name: /a1_ign/odometry
  gz_type_name: ignition.msgs.Odometry
  ros_type_name: nav_msgs/msg/Odometry
  direction: GZ_TO_ROS